/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.boxalino.p13n.api.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FacetResponse implements org.apache.thrift.TBase<FacetResponse, FacetResponse._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FacetResponse");

  private static final org.apache.thrift.protocol.TField FIELD_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("fieldName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField STRING_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("stringValue", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField RANGE_FROM_INCLUSIVE_FIELD_DESC = new org.apache.thrift.protocol.TField("rangeFromInclusive", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField RANGE_TO_EXCLUSIVE_FIELD_DESC = new org.apache.thrift.protocol.TField("rangeToExclusive", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField HIT_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("hitCount", org.apache.thrift.protocol.TType.I64, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FacetResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FacetResponseTupleSchemeFactory());
  }

  public String fieldName; // required
  public String stringValue; // required
  public String rangeFromInclusive; // required
  public String rangeToExclusive; // required
  public long hitCount; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FIELD_NAME((short)1, "fieldName"),
    STRING_VALUE((short)2, "stringValue"),
    RANGE_FROM_INCLUSIVE((short)3, "rangeFromInclusive"),
    RANGE_TO_EXCLUSIVE((short)4, "rangeToExclusive"),
    HIT_COUNT((short)5, "hitCount");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FIELD_NAME
          return FIELD_NAME;
        case 2: // STRING_VALUE
          return STRING_VALUE;
        case 3: // RANGE_FROM_INCLUSIVE
          return RANGE_FROM_INCLUSIVE;
        case 4: // RANGE_TO_EXCLUSIVE
          return RANGE_TO_EXCLUSIVE;
        case 5: // HIT_COUNT
          return HIT_COUNT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HITCOUNT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FIELD_NAME, new org.apache.thrift.meta_data.FieldMetaData("fieldName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STRING_VALUE, new org.apache.thrift.meta_data.FieldMetaData("stringValue", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RANGE_FROM_INCLUSIVE, new org.apache.thrift.meta_data.FieldMetaData("rangeFromInclusive", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RANGE_TO_EXCLUSIVE, new org.apache.thrift.meta_data.FieldMetaData("rangeToExclusive", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HIT_COUNT, new org.apache.thrift.meta_data.FieldMetaData("hitCount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FacetResponse.class, metaDataMap);
  }

  public FacetResponse() {
  }

  public FacetResponse(
    String fieldName,
    String stringValue,
    String rangeFromInclusive,
    String rangeToExclusive,
    long hitCount)
  {
    this();
    this.fieldName = fieldName;
    this.stringValue = stringValue;
    this.rangeFromInclusive = rangeFromInclusive;
    this.rangeToExclusive = rangeToExclusive;
    this.hitCount = hitCount;
    setHitCountIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FacetResponse(FacetResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetFieldName()) {
      this.fieldName = other.fieldName;
    }
    if (other.isSetStringValue()) {
      this.stringValue = other.stringValue;
    }
    if (other.isSetRangeFromInclusive()) {
      this.rangeFromInclusive = other.rangeFromInclusive;
    }
    if (other.isSetRangeToExclusive()) {
      this.rangeToExclusive = other.rangeToExclusive;
    }
    this.hitCount = other.hitCount;
  }

  public FacetResponse deepCopy() {
    return new FacetResponse(this);
  }

  @Override
  public void clear() {
    this.fieldName = null;
    this.stringValue = null;
    this.rangeFromInclusive = null;
    this.rangeToExclusive = null;
    setHitCountIsSet(false);
    this.hitCount = 0;
  }

  public String getFieldName() {
    return this.fieldName;
  }

  public FacetResponse setFieldName(String fieldName) {
    this.fieldName = fieldName;
    return this;
  }

  public void unsetFieldName() {
    this.fieldName = null;
  }

  /** Returns true if field fieldName is set (has been assigned a value) and false otherwise */
  public boolean isSetFieldName() {
    return this.fieldName != null;
  }

  public void setFieldNameIsSet(boolean value) {
    if (!value) {
      this.fieldName = null;
    }
  }

  public String getStringValue() {
    return this.stringValue;
  }

  public FacetResponse setStringValue(String stringValue) {
    this.stringValue = stringValue;
    return this;
  }

  public void unsetStringValue() {
    this.stringValue = null;
  }

  /** Returns true if field stringValue is set (has been assigned a value) and false otherwise */
  public boolean isSetStringValue() {
    return this.stringValue != null;
  }

  public void setStringValueIsSet(boolean value) {
    if (!value) {
      this.stringValue = null;
    }
  }

  public String getRangeFromInclusive() {
    return this.rangeFromInclusive;
  }

  public FacetResponse setRangeFromInclusive(String rangeFromInclusive) {
    this.rangeFromInclusive = rangeFromInclusive;
    return this;
  }

  public void unsetRangeFromInclusive() {
    this.rangeFromInclusive = null;
  }

  /** Returns true if field rangeFromInclusive is set (has been assigned a value) and false otherwise */
  public boolean isSetRangeFromInclusive() {
    return this.rangeFromInclusive != null;
  }

  public void setRangeFromInclusiveIsSet(boolean value) {
    if (!value) {
      this.rangeFromInclusive = null;
    }
  }

  public String getRangeToExclusive() {
    return this.rangeToExclusive;
  }

  public FacetResponse setRangeToExclusive(String rangeToExclusive) {
    this.rangeToExclusive = rangeToExclusive;
    return this;
  }

  public void unsetRangeToExclusive() {
    this.rangeToExclusive = null;
  }

  /** Returns true if field rangeToExclusive is set (has been assigned a value) and false otherwise */
  public boolean isSetRangeToExclusive() {
    return this.rangeToExclusive != null;
  }

  public void setRangeToExclusiveIsSet(boolean value) {
    if (!value) {
      this.rangeToExclusive = null;
    }
  }

  public long getHitCount() {
    return this.hitCount;
  }

  public FacetResponse setHitCount(long hitCount) {
    this.hitCount = hitCount;
    setHitCountIsSet(true);
    return this;
  }

  public void unsetHitCount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HITCOUNT_ISSET_ID);
  }

  /** Returns true if field hitCount is set (has been assigned a value) and false otherwise */
  public boolean isSetHitCount() {
    return EncodingUtils.testBit(__isset_bitfield, __HITCOUNT_ISSET_ID);
  }

  public void setHitCountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HITCOUNT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FIELD_NAME:
      if (value == null) {
        unsetFieldName();
      } else {
        setFieldName((String)value);
      }
      break;

    case STRING_VALUE:
      if (value == null) {
        unsetStringValue();
      } else {
        setStringValue((String)value);
      }
      break;

    case RANGE_FROM_INCLUSIVE:
      if (value == null) {
        unsetRangeFromInclusive();
      } else {
        setRangeFromInclusive((String)value);
      }
      break;

    case RANGE_TO_EXCLUSIVE:
      if (value == null) {
        unsetRangeToExclusive();
      } else {
        setRangeToExclusive((String)value);
      }
      break;

    case HIT_COUNT:
      if (value == null) {
        unsetHitCount();
      } else {
        setHitCount((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FIELD_NAME:
      return getFieldName();

    case STRING_VALUE:
      return getStringValue();

    case RANGE_FROM_INCLUSIVE:
      return getRangeFromInclusive();

    case RANGE_TO_EXCLUSIVE:
      return getRangeToExclusive();

    case HIT_COUNT:
      return Long.valueOf(getHitCount());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FIELD_NAME:
      return isSetFieldName();
    case STRING_VALUE:
      return isSetStringValue();
    case RANGE_FROM_INCLUSIVE:
      return isSetRangeFromInclusive();
    case RANGE_TO_EXCLUSIVE:
      return isSetRangeToExclusive();
    case HIT_COUNT:
      return isSetHitCount();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FacetResponse)
      return this.equals((FacetResponse)that);
    return false;
  }

  public boolean equals(FacetResponse that) {
    if (that == null)
      return false;

    boolean this_present_fieldName = true && this.isSetFieldName();
    boolean that_present_fieldName = true && that.isSetFieldName();
    if (this_present_fieldName || that_present_fieldName) {
      if (!(this_present_fieldName && that_present_fieldName))
        return false;
      if (!this.fieldName.equals(that.fieldName))
        return false;
    }

    boolean this_present_stringValue = true && this.isSetStringValue();
    boolean that_present_stringValue = true && that.isSetStringValue();
    if (this_present_stringValue || that_present_stringValue) {
      if (!(this_present_stringValue && that_present_stringValue))
        return false;
      if (!this.stringValue.equals(that.stringValue))
        return false;
    }

    boolean this_present_rangeFromInclusive = true && this.isSetRangeFromInclusive();
    boolean that_present_rangeFromInclusive = true && that.isSetRangeFromInclusive();
    if (this_present_rangeFromInclusive || that_present_rangeFromInclusive) {
      if (!(this_present_rangeFromInclusive && that_present_rangeFromInclusive))
        return false;
      if (!this.rangeFromInclusive.equals(that.rangeFromInclusive))
        return false;
    }

    boolean this_present_rangeToExclusive = true && this.isSetRangeToExclusive();
    boolean that_present_rangeToExclusive = true && that.isSetRangeToExclusive();
    if (this_present_rangeToExclusive || that_present_rangeToExclusive) {
      if (!(this_present_rangeToExclusive && that_present_rangeToExclusive))
        return false;
      if (!this.rangeToExclusive.equals(that.rangeToExclusive))
        return false;
    }

    boolean this_present_hitCount = true;
    boolean that_present_hitCount = true;
    if (this_present_hitCount || that_present_hitCount) {
      if (!(this_present_hitCount && that_present_hitCount))
        return false;
      if (this.hitCount != that.hitCount)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(FacetResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    FacetResponse typedOther = (FacetResponse)other;

    lastComparison = Boolean.valueOf(isSetFieldName()).compareTo(typedOther.isSetFieldName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFieldName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fieldName, typedOther.fieldName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStringValue()).compareTo(typedOther.isSetStringValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStringValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stringValue, typedOther.stringValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRangeFromInclusive()).compareTo(typedOther.isSetRangeFromInclusive());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRangeFromInclusive()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rangeFromInclusive, typedOther.rangeFromInclusive);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRangeToExclusive()).compareTo(typedOther.isSetRangeToExclusive());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRangeToExclusive()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rangeToExclusive, typedOther.rangeToExclusive);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHitCount()).compareTo(typedOther.isSetHitCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHitCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hitCount, typedOther.hitCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FacetResponse(");
    boolean first = true;

    sb.append("fieldName:");
    if (this.fieldName == null) {
      sb.append("null");
    } else {
      sb.append(this.fieldName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("stringValue:");
    if (this.stringValue == null) {
      sb.append("null");
    } else {
      sb.append(this.stringValue);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("rangeFromInclusive:");
    if (this.rangeFromInclusive == null) {
      sb.append("null");
    } else {
      sb.append(this.rangeFromInclusive);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("rangeToExclusive:");
    if (this.rangeToExclusive == null) {
      sb.append("null");
    } else {
      sb.append(this.rangeToExclusive);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("hitCount:");
    sb.append(this.hitCount);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FacetResponseStandardSchemeFactory implements SchemeFactory {
    public FacetResponseStandardScheme getScheme() {
      return new FacetResponseStandardScheme();
    }
  }

  private static class FacetResponseStandardScheme extends StandardScheme<FacetResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FacetResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FIELD_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fieldName = iprot.readString();
              struct.setFieldNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STRING_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.stringValue = iprot.readString();
              struct.setStringValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // RANGE_FROM_INCLUSIVE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.rangeFromInclusive = iprot.readString();
              struct.setRangeFromInclusiveIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // RANGE_TO_EXCLUSIVE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.rangeToExclusive = iprot.readString();
              struct.setRangeToExclusiveIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // HIT_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.hitCount = iprot.readI64();
              struct.setHitCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FacetResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.fieldName != null) {
        oprot.writeFieldBegin(FIELD_NAME_FIELD_DESC);
        oprot.writeString(struct.fieldName);
        oprot.writeFieldEnd();
      }
      if (struct.stringValue != null) {
        oprot.writeFieldBegin(STRING_VALUE_FIELD_DESC);
        oprot.writeString(struct.stringValue);
        oprot.writeFieldEnd();
      }
      if (struct.rangeFromInclusive != null) {
        oprot.writeFieldBegin(RANGE_FROM_INCLUSIVE_FIELD_DESC);
        oprot.writeString(struct.rangeFromInclusive);
        oprot.writeFieldEnd();
      }
      if (struct.rangeToExclusive != null) {
        oprot.writeFieldBegin(RANGE_TO_EXCLUSIVE_FIELD_DESC);
        oprot.writeString(struct.rangeToExclusive);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(HIT_COUNT_FIELD_DESC);
      oprot.writeI64(struct.hitCount);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FacetResponseTupleSchemeFactory implements SchemeFactory {
    public FacetResponseTupleScheme getScheme() {
      return new FacetResponseTupleScheme();
    }
  }

  private static class FacetResponseTupleScheme extends TupleScheme<FacetResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FacetResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFieldName()) {
        optionals.set(0);
      }
      if (struct.isSetStringValue()) {
        optionals.set(1);
      }
      if (struct.isSetRangeFromInclusive()) {
        optionals.set(2);
      }
      if (struct.isSetRangeToExclusive()) {
        optionals.set(3);
      }
      if (struct.isSetHitCount()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetFieldName()) {
        oprot.writeString(struct.fieldName);
      }
      if (struct.isSetStringValue()) {
        oprot.writeString(struct.stringValue);
      }
      if (struct.isSetRangeFromInclusive()) {
        oprot.writeString(struct.rangeFromInclusive);
      }
      if (struct.isSetRangeToExclusive()) {
        oprot.writeString(struct.rangeToExclusive);
      }
      if (struct.isSetHitCount()) {
        oprot.writeI64(struct.hitCount);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FacetResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.fieldName = iprot.readString();
        struct.setFieldNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.stringValue = iprot.readString();
        struct.setStringValueIsSet(true);
      }
      if (incoming.get(2)) {
        struct.rangeFromInclusive = iprot.readString();
        struct.setRangeFromInclusiveIsSet(true);
      }
      if (incoming.get(3)) {
        struct.rangeToExclusive = iprot.readString();
        struct.setRangeToExclusiveIsSet(true);
      }
      if (incoming.get(4)) {
        struct.hitCount = iprot.readI64();
        struct.setHitCountIsSet(true);
      }
    }
  }

}

