/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.boxalino.p13n.api.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SearchRelaxation implements org.apache.thrift.TBase<SearchRelaxation, SearchRelaxation._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SearchRelaxation");

  private static final org.apache.thrift.protocol.TField SUGGESTIONS_RESULTS_FIELD_DESC = new org.apache.thrift.protocol.TField("suggestionsResults", org.apache.thrift.protocol.TType.LIST, (short)10);
  private static final org.apache.thrift.protocol.TField SUBPHRASES_RESULTS_FIELD_DESC = new org.apache.thrift.protocol.TField("subphrasesResults", org.apache.thrift.protocol.TType.LIST, (short)20);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SearchRelaxationStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SearchRelaxationTupleSchemeFactory());
  }

  public List<SearchResult> suggestionsResults; // required
  public List<SearchResult> subphrasesResults; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SUGGESTIONS_RESULTS((short)10, "suggestionsResults"),
    SUBPHRASES_RESULTS((short)20, "subphrasesResults");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 10: // SUGGESTIONS_RESULTS
          return SUGGESTIONS_RESULTS;
        case 20: // SUBPHRASES_RESULTS
          return SUBPHRASES_RESULTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SUGGESTIONS_RESULTS, new org.apache.thrift.meta_data.FieldMetaData("suggestionsResults", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SearchResult.class))));
    tmpMap.put(_Fields.SUBPHRASES_RESULTS, new org.apache.thrift.meta_data.FieldMetaData("subphrasesResults", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SearchResult.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SearchRelaxation.class, metaDataMap);
  }

  public SearchRelaxation() {
  }

  public SearchRelaxation(
    List<SearchResult> suggestionsResults,
    List<SearchResult> subphrasesResults)
  {
    this();
    this.suggestionsResults = suggestionsResults;
    this.subphrasesResults = subphrasesResults;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SearchRelaxation(SearchRelaxation other) {
    if (other.isSetSuggestionsResults()) {
      List<SearchResult> __this__suggestionsResults = new ArrayList<SearchResult>();
      for (SearchResult other_element : other.suggestionsResults) {
        __this__suggestionsResults.add(new SearchResult(other_element));
      }
      this.suggestionsResults = __this__suggestionsResults;
    }
    if (other.isSetSubphrasesResults()) {
      List<SearchResult> __this__subphrasesResults = new ArrayList<SearchResult>();
      for (SearchResult other_element : other.subphrasesResults) {
        __this__subphrasesResults.add(new SearchResult(other_element));
      }
      this.subphrasesResults = __this__subphrasesResults;
    }
  }

  public SearchRelaxation deepCopy() {
    return new SearchRelaxation(this);
  }

  @Override
  public void clear() {
    this.suggestionsResults = null;
    this.subphrasesResults = null;
  }

  public int getSuggestionsResultsSize() {
    return (this.suggestionsResults == null) ? 0 : this.suggestionsResults.size();
  }

  public java.util.Iterator<SearchResult> getSuggestionsResultsIterator() {
    return (this.suggestionsResults == null) ? null : this.suggestionsResults.iterator();
  }

  public void addToSuggestionsResults(SearchResult elem) {
    if (this.suggestionsResults == null) {
      this.suggestionsResults = new ArrayList<SearchResult>();
    }
    this.suggestionsResults.add(elem);
  }

  public List<SearchResult> getSuggestionsResults() {
    return this.suggestionsResults;
  }

  public SearchRelaxation setSuggestionsResults(List<SearchResult> suggestionsResults) {
    this.suggestionsResults = suggestionsResults;
    return this;
  }

  public void unsetSuggestionsResults() {
    this.suggestionsResults = null;
  }

  /** Returns true if field suggestionsResults is set (has been assigned a value) and false otherwise */
  public boolean isSetSuggestionsResults() {
    return this.suggestionsResults != null;
  }

  public void setSuggestionsResultsIsSet(boolean value) {
    if (!value) {
      this.suggestionsResults = null;
    }
  }

  public int getSubphrasesResultsSize() {
    return (this.subphrasesResults == null) ? 0 : this.subphrasesResults.size();
  }

  public java.util.Iterator<SearchResult> getSubphrasesResultsIterator() {
    return (this.subphrasesResults == null) ? null : this.subphrasesResults.iterator();
  }

  public void addToSubphrasesResults(SearchResult elem) {
    if (this.subphrasesResults == null) {
      this.subphrasesResults = new ArrayList<SearchResult>();
    }
    this.subphrasesResults.add(elem);
  }

  public List<SearchResult> getSubphrasesResults() {
    return this.subphrasesResults;
  }

  public SearchRelaxation setSubphrasesResults(List<SearchResult> subphrasesResults) {
    this.subphrasesResults = subphrasesResults;
    return this;
  }

  public void unsetSubphrasesResults() {
    this.subphrasesResults = null;
  }

  /** Returns true if field subphrasesResults is set (has been assigned a value) and false otherwise */
  public boolean isSetSubphrasesResults() {
    return this.subphrasesResults != null;
  }

  public void setSubphrasesResultsIsSet(boolean value) {
    if (!value) {
      this.subphrasesResults = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SUGGESTIONS_RESULTS:
      if (value == null) {
        unsetSuggestionsResults();
      } else {
        setSuggestionsResults((List<SearchResult>)value);
      }
      break;

    case SUBPHRASES_RESULTS:
      if (value == null) {
        unsetSubphrasesResults();
      } else {
        setSubphrasesResults((List<SearchResult>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SUGGESTIONS_RESULTS:
      return getSuggestionsResults();

    case SUBPHRASES_RESULTS:
      return getSubphrasesResults();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SUGGESTIONS_RESULTS:
      return isSetSuggestionsResults();
    case SUBPHRASES_RESULTS:
      return isSetSubphrasesResults();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SearchRelaxation)
      return this.equals((SearchRelaxation)that);
    return false;
  }

  public boolean equals(SearchRelaxation that) {
    if (that == null)
      return false;

    boolean this_present_suggestionsResults = true && this.isSetSuggestionsResults();
    boolean that_present_suggestionsResults = true && that.isSetSuggestionsResults();
    if (this_present_suggestionsResults || that_present_suggestionsResults) {
      if (!(this_present_suggestionsResults && that_present_suggestionsResults))
        return false;
      if (!this.suggestionsResults.equals(that.suggestionsResults))
        return false;
    }

    boolean this_present_subphrasesResults = true && this.isSetSubphrasesResults();
    boolean that_present_subphrasesResults = true && that.isSetSubphrasesResults();
    if (this_present_subphrasesResults || that_present_subphrasesResults) {
      if (!(this_present_subphrasesResults && that_present_subphrasesResults))
        return false;
      if (!this.subphrasesResults.equals(that.subphrasesResults))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(SearchRelaxation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    SearchRelaxation typedOther = (SearchRelaxation)other;

    lastComparison = Boolean.valueOf(isSetSuggestionsResults()).compareTo(typedOther.isSetSuggestionsResults());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSuggestionsResults()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.suggestionsResults, typedOther.suggestionsResults);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSubphrasesResults()).compareTo(typedOther.isSetSubphrasesResults());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSubphrasesResults()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.subphrasesResults, typedOther.subphrasesResults);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SearchRelaxation(");
    boolean first = true;

    sb.append("suggestionsResults:");
    if (this.suggestionsResults == null) {
      sb.append("null");
    } else {
      sb.append(this.suggestionsResults);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("subphrasesResults:");
    if (this.subphrasesResults == null) {
      sb.append("null");
    } else {
      sb.append(this.subphrasesResults);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SearchRelaxationStandardSchemeFactory implements SchemeFactory {
    public SearchRelaxationStandardScheme getScheme() {
      return new SearchRelaxationStandardScheme();
    }
  }

  private static class SearchRelaxationStandardScheme extends StandardScheme<SearchRelaxation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SearchRelaxation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 10: // SUGGESTIONS_RESULTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list148 = iprot.readListBegin();
                struct.suggestionsResults = new ArrayList<SearchResult>(_list148.size);
                for (int _i149 = 0; _i149 < _list148.size; ++_i149)
                {
                  SearchResult _elem150; // required
                  _elem150 = new SearchResult();
                  _elem150.read(iprot);
                  struct.suggestionsResults.add(_elem150);
                }
                iprot.readListEnd();
              }
              struct.setSuggestionsResultsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 20: // SUBPHRASES_RESULTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list151 = iprot.readListBegin();
                struct.subphrasesResults = new ArrayList<SearchResult>(_list151.size);
                for (int _i152 = 0; _i152 < _list151.size; ++_i152)
                {
                  SearchResult _elem153; // required
                  _elem153 = new SearchResult();
                  _elem153.read(iprot);
                  struct.subphrasesResults.add(_elem153);
                }
                iprot.readListEnd();
              }
              struct.setSubphrasesResultsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SearchRelaxation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.suggestionsResults != null) {
        oprot.writeFieldBegin(SUGGESTIONS_RESULTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.suggestionsResults.size()));
          for (SearchResult _iter154 : struct.suggestionsResults)
          {
            _iter154.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.subphrasesResults != null) {
        oprot.writeFieldBegin(SUBPHRASES_RESULTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.subphrasesResults.size()));
          for (SearchResult _iter155 : struct.subphrasesResults)
          {
            _iter155.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SearchRelaxationTupleSchemeFactory implements SchemeFactory {
    public SearchRelaxationTupleScheme getScheme() {
      return new SearchRelaxationTupleScheme();
    }
  }

  private static class SearchRelaxationTupleScheme extends TupleScheme<SearchRelaxation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SearchRelaxation struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSuggestionsResults()) {
        optionals.set(0);
      }
      if (struct.isSetSubphrasesResults()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSuggestionsResults()) {
        {
          oprot.writeI32(struct.suggestionsResults.size());
          for (SearchResult _iter156 : struct.suggestionsResults)
          {
            _iter156.write(oprot);
          }
        }
      }
      if (struct.isSetSubphrasesResults()) {
        {
          oprot.writeI32(struct.subphrasesResults.size());
          for (SearchResult _iter157 : struct.subphrasesResults)
          {
            _iter157.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SearchRelaxation struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list158 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.suggestionsResults = new ArrayList<SearchResult>(_list158.size);
          for (int _i159 = 0; _i159 < _list158.size; ++_i159)
          {
            SearchResult _elem160; // required
            _elem160 = new SearchResult();
            _elem160.read(iprot);
            struct.suggestionsResults.add(_elem160);
          }
        }
        struct.setSuggestionsResultsIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list161 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.subphrasesResults = new ArrayList<SearchResult>(_list161.size);
          for (int _i162 = 0; _i162 < _list161.size; ++_i162)
          {
            SearchResult _elem163; // required
            _elem163 = new SearchResult();
            _elem163.read(iprot);
            struct.subphrasesResults.add(_elem163);
          }
        }
        struct.setSubphrasesResultsIsSet(true);
      }
    }
  }

}

